blueprint:
  name: IKEA E1743 Zigbee2MQTT - Short/Long or Short/Double Press
  description: >
    Simple controller automation for IKEA E1743 TRÅDFRI On/Off Switch using Zigbee2MQTT.
  domain: automation
  homeassistant:
    min_version: 2024.10.0
  input:
    controller_device:
      name: Controller Device
      description: The IKEA E1743 switch integrated via Zigbee2MQTT.
      selector:
        device:
          filter:
            - integration: mqtt
              manufacturer: IKEA
              model: TRADFRI on/off switch
          multiple: false
    helper_last_controller_event:
      name: Helper - Last Controller Event
      description: Input Text used to store the last event fired by the controller.
      selector:
        entity:
          domain: input_text
    action_button_up_short:
      name: Up button short press
      default: []
      selector:
        action:
    action_button_up_long_or_double:
      name: Up button long press or double press
      default: []
      selector:
        action:
    action_button_down_short:
      name: Down button short press
      default: []
      selector:
        action:
    action_button_down_long_or_double:
      name: Down button long press or double press
      default: []
      selector:
        action:
    helper_double_press_delay:
      name: Helper - Double Press delay
      default: 500
      selector:
        number:
          min: 100
          max: 5000
          unit_of_measurement: milliseconds
          mode: box
          step: 10
    helper_debounce_delay:
      name: Helper - Debounce delay
      default: 0
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: milliseconds
          mode: box
          step: 10

variables:
  controller_id: !input controller_device
  button_up_short: ['on']
  button_up_long_or_double: [brightness_move_up]
  button_down_short: ['off']
  button_down_long_or_double: [brightness_move_down]

mode: restart
max_exceeded: silent

triggers:
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: on
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: off
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: brightness_move_up
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: brightness_move_down

actions:
  - delay:
      milliseconds: !input helper_debounce_delay
  - variables:
      trigger_action: '{{ trigger.payload }}'
      deserialized_state: '{{ (states(helper_last_controller_event) | from_json) if helper_last_controller_event is not none else {} }}'
      trigger_delta: '{{ (as_timestamp(now()) - (deserialized_state.t | default(0))) * 1000 }}'
      last_controller_event: '{{ (deserialized_state.a | default("")) }}'
  - service: input_text.set_value
    data:
      entity_id: !input helper_last_controller_event
      value: '{{ {"a":trigger_action,"t":as_timestamp(now())} | to_json }}'
  - choose:
      - conditions: '{{ trigger_action in button_up_short }}'
        sequence:
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_up_short
          - choose:
              - conditions: []
                sequence: !input action_button_up_short
      - conditions: '{{ trigger_action in button_up_long_or_double }}'
        sequence:
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_up_long_or_double
          - choose:
              - conditions: []
                sequence: !input action_button_up_long_or_double
      - conditions: '{{ trigger_action in button_down_short }}'
        sequence:
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_down_short
          - choose:
              - conditions: []
                sequence: !input action_button_down_short
      - conditions: '{{ trigger_action in button_down_long_or_double }}'
        sequence:
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_down_long_or_double
          - choose:
              - conditions: []
                sequence: !input action_button_down_long_or_double
