blueprint:
  name: Controller - IKEA E1743 TRÅDFRI On/Off Switch & Dimmer (Zigbee2MQTT)
  description: >
    Controller automation for executing actions triggered by IKEA E1743 TRÅDFRI On/Off Switch & Dimmer using Zigbee2MQTT.
  domain: automation
  homeassistant:
    min_version: 2024.10.0
  input:
    controller_device:
      name: Controller Device
      description: The IKEA E1743 switch integrated via Zigbee2MQTT.
      selector:
        device:
          filter:
            - integration: mqtt
              manufacturer: IKEA
              model: TRADFRI on/off switch
          multiple: false
    helper_last_controller_event:
      name: Helper - Last Controller Event
      description: Input Text used to store the last event fired by the controller.
      selector:
        entity:
          domain: input_text
    action_button_up_short:
      name: Up button short press
      default: []
      selector:
        action:
    action_button_up_long:
      name: Up button long press
      default: []
      selector:
        action:
    action_button_up_release:
      name: Up button release
      default: []
      selector:
        action:
    action_button_up_double:
      name: Up button double press
      default: []
      selector:
        action:
    action_button_down_short:
      name: Down button short press
      default: []
      selector:
        action:
    action_button_down_long:
      name: Down button long press
      default: []
      selector:
        action:
    action_button_down_release:
      name: Down button release
      default: []
      selector:
        action:
    action_button_down_double:
      name: Down button double press
      default: []
      selector:
        action:
    button_up_long_loop:
      name: Up button long press - loop until release
      default: false
      selector:
        boolean:
    button_up_long_max_loop_repeats:
      name: Up button long press - Maximum loop repeats
      default: 500
      selector:
        number:
          min: 1
          max: 5000
          mode: slider
          step: 1
    button_down_long_loop:
      name: Down button long press - loop until release
      default: false
      selector:
        boolean:
    button_down_long_max_loop_repeats:
      name: Down button long press - Maximum loop repeats
      default: 500
      selector:
        number:
          min: 1
          max: 5000
          mode: slider
          step: 1
    button_up_double_press:
      name: Expose up button double press
      default: false
      selector:
        boolean:
    button_down_double_press:
      name: Expose down button double press
      default: false
      selector:
        boolean:
    helper_double_press_delay:
      name: Helper - Double Press delay
      default: 500
      selector:
        number:
          min: 100
          max: 5000
          unit_of_measurement: milliseconds
          mode: box
          step: 10
    helper_debounce_delay:
      name: Helper - Debounce delay
      default: 0
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: milliseconds
          mode: box
          step: 10

variables:
  integration_id: 'zigbee2mqtt'
  controller_id: !input controller_device
  button_up_short: ['on']
  button_up_long: [brightness_move_up]
  button_up_release: [brightness_stop]
  button_down_short: ['off']
  button_down_long: [brightness_move_down]
  button_down_release: [brightness_stop]

mode: restart
max_exceeded: silent

triggers:
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: on
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: off
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: brightness_move_up
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: brightness_move_down
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: brightness_stop

actions:
  - delay:
      milliseconds: !input helper_debounce_delay
  - variables:
      trigger_action: '{{ trigger.payload }}'
      deserialized_state: '{{ (states(helper_last_controller_event) | from_json) if helper_last_controller_event is not none else {} }}'
      trigger_delta: '{{ (as_timestamp(now()) - (deserialized_state.t | default(0))) * 1000 }}'
      last_controller_event: '{{ (deserialized_state.a | default("")) }}'
  - service: input_text.set_value
    data:
      entity_id: !input helper_last_controller_event
      value: '{{ {"a":trigger_action,"t":as_timestamp(now())} | to_json }}'
  - choose:
      - conditions: '{{ trigger_action in button_up_short }}'
        sequence:
          - choose:
              - conditions: '{{ button_up_double_press }}'
                sequence:
                  - choose:
                      - conditions: '{{ trigger_action == last_controller_event and trigger_delta <= helper_double_press_delay }}'
                        sequence:
                          - service: input_text.set_value
                            data:
                              entity_id: !input helper_last_controller_event
                              value: '{{ {"a":"double_press_up","t":as_timestamp(now())} | to_json }}'
                          - event: ahb_controller_event
                            event_data:
                              controller: '{{ controller_id }}'
                              action: button_up_double
                          - choose:
                              - conditions: []
                                sequence: !input action_button_up_double
                    default:
                      - delay:
                          milliseconds: '{{ helper_double_press_delay }}'
                      - event: ahb_controller_event
                        event_data:
                          controller: '{{ controller_id }}'
                          action: button_up_short
                      - choose:
                          - conditions: []
                            sequence: !input action_button_up_short
            default:
              - event: ahb_controller_event
                event_data:
                  controller: '{{ controller_id }}'
                  action: button_up_short
              - choose:
                  - conditions: []
                    sequence: !input action_button_up_short
      - conditions: '{{ trigger_action in button_up_long }}'
        sequence:
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_up_long
          - choose:
              - conditions: '{{ button_up_long_loop }}'
                sequence:
                  - repeat:
                      while: '{{ repeat.index < button_up_long_max_loop_repeats }}'
                      sequence: !input action_button_up_long
            default: !input action_button_up_long
      - conditions: '{{ trigger_action in button_up_release }}'
        sequence:
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_up_release
          - choose:
              - conditions: []
                sequence: !input action_button_up_release
      - conditions: '{{ trigger_action in button_down_short }}'
        sequence:
          - choose:
              - conditions: '{{ button_down_double_press }}'
                sequence:
                  - choose:
                      - conditions: '{{ trigger_action == last_controller_event and trigger_delta <= helper_double_press_delay }}'
                        sequence:
                          - service: input_text.set_value
                            data:
                              entity_id: !input helper_last_controller_event
                              value: '{{ {"a":"double_press_down","t":as_timestamp(now())} | to_json }}'
                          - event: ahb_controller_event
                            event_data:
                              controller: '{{ controller_id }}'
                              action: button_down_double
                          - choose:
                              - conditions: []
                                sequence: !input action_button_down_double
                    default:
                      - delay:
                          milliseconds: '{{ helper_double_press_delay }}'
                      - event: ahb_controller_event
                        event_data:
                          controller: '{{ controller_id }}'
                          action: button_down_short
                      - choose:
                          - conditions: []
                            sequence: !input action_button_down_short
            default:
              - event: ahb_controller_event
                event_data:
                  controller: '{{ controller_id }}'
                  action: button_down_short
              - choose:
                  - conditions: []
                    sequence: !input action_button_down_short
      - conditions: '{{ trigger_action in button_down_long }}'
        sequence:
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_down_long
          - choose:
              - conditions: '{{ button_down_long_loop }}'
                sequence:
                  - repeat:
                      while: '{{ repeat.index < button_down_long_max_loop_repeats }}'
                      sequence: !input action_button_down_long
            default: !input action_button_down_long
      - conditions: '{{ trigger_action in button_down_release }}'
        sequence:
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_down_release
          - choose:
              - conditions: []
                sequence: !input action_button_down_release
