blueprint:
  name: IKEA E1743 TRÅDFRI On/Off Switch - Zigbee2MQTT Minimal
  description: Automation für IKEA E1743 über Zigbee2MQTT
  domain: automation
  homeassistant:
    min_version: 2024.10.0
  input:
    controller_device:
      name: Controller Device
      selector:
        device:
          filter:
            - integration: mqtt
              manufacturer: IKEA
              model: TRADFRI on/off switch
          multiple: false
    helper_last_controller_event:
      name: Helper Last Controller Event
      selector:
        entity:
          domain: input_text
    action_up_short:
      name: Up Short Press
      selector:
        action: {}
    action_up_long:
      name: Up Long Press
      selector:
        action: {}
    action_up_release:
      name: Up Release
      selector:
        action: {}
    action_down_short:
      name: Down Short Press
      selector:
        action: {}
    action_down_long:
      name: Down Long Press
      selector:
        action: {}
    action_down_release:
      name: Down Release
      selector:
        action: {}

variables:
  controller_id: !input controller_device
  actions:
    up_short: !input action_up_short
    up_long: !input action_up_long
    up_release: !input action_up_release
    down_short: !input action_down_short
    down_long: !input action_down_long
    down_release: !input action_down_release

mode: restart

triggers:
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: on
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: off
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: brightness_move_up
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: brightness_move_down
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: brightness_stop

actions:
  - variables:
      trigger_action: '{{ trigger.payload }}'
  - action: input_text.set_value
    data:
      entity_id: !input helper_last_controller_event
      value: '{{ {"a":trigger_action,"t":as_timestamp(now())} | to_json }}'
  - choose:
      - conditions: '{{ trigger_action == "on" }}'
        sequence: !input action_up_short
      - conditions: '{{ trigger_action == "brightness_move_up" }}'
        sequence: !input action_up_long
      - conditions: '{{ trigger_action == "brightness_stop" }}'
        sequence: !input action_up_release
      - conditions: '{{ trigger_action == "off" }}'
        sequence: !input action_down_short
      - conditions: '{{ trigger_action == "brightness_move_down" }}'
        sequence: !input action_down_long
      - conditions: '{{ trigger_action == "brightness_stop" }}'
        sequence: !input action_down_release
