blueprint:
  name: Shelly i4 Multi-Press Sensor Automation
  description: >
    Automatisierung für Shelly i4 Tasten über Sensoren. Unterstützt Short Press, Long Press, Single Press und Double Press.
    Du kannst jeden Shelly i4 Sensor aus der Shelly Integration auswählen.
  domain: automation

  input:
    shelly_sensor:
      name: Shelly i4 Sensor
      description: Wähle den Sensor aus, der die Taste meldet
      selector:
        entity:
          domain: sensor
          integration: shelly

    short_press_action:
      name: Short Press Aktion
      description: Aktion, die bei einem kurzen Tastendruck ausgeführt wird
      selector:
        action: {}

    long_press_action:
      name: Long Press Aktion
      description: Aktion, die bei einem langen Tastendruck ausgeführt wird
      selector:
        action: {}

    single_press_action:
      name: Single Press Aktion
      description: Aktion, die bei einem einfachen Klick ausgeführt wird
      selector:
        action: {}

    double_press_action:
      name: Double Press Aktion
      description: Aktion, die bei einem doppelten Klick ausgeführt wird
      selector:
        action: {}

trigger:
  - platform: state
    entity_id: !input "shelly_sensor"

variables:
  event: "{{ trigger.to_state.state }}"

action:
  - choose:
      - conditions: "{{ event in ['shortpush', 'S1_short', 'S2_short', 'S3_short', 'S4_short'] }}"
        sequence: !input "short_press_action"
      - conditions: "{{ event in ['longpush', 'S1_long', 'S2_long', 'S3_long', 'S4_long'] }}"
        sequence: !input "long_press_action"
      - conditions: "{{ event in ['single', 'S1_single', 'S2_single', 'S3_single', 'S4_single'] }}"
        sequence: !input "single_press_action"
      - conditions: "{{ event in ['double', 'S1_double', 'S2_double', 'S3_double', 'S4_double'] }}"
        sequence: !input "double_press_action"
