blueprint:
  name: Shelly i4 Gen3 – Alle Aktionen (24 Felder)
  description: >
    Wähle dein Shelly i4 Gen3 Gerät aus. 
    Alle 24 Aktionen (4 Eingänge × 6 Events) stehen untereinander als einzelne Felder zur Verfügung.
  domain: automation

  input:
    shelly_device:
      name: Shelly i4 Gen3 Gerät
      selector:
        device:
          integration: mqtt
          manufacturer: Shelly

    # Eingang 0
    in0_btn_down:
      name: Eingang 0 – btn_down
      selector: { action: {} }
      default: []
    in0_btn_up:
      name: Eingang 0 – btn_up
      selector: { action: {} }
      default: []
    in0_single_push:
      name: Eingang 0 – single_push
      selector: { action: {} }
      default: []
    in0_double_push:
      name: Eingang 0 – double_push
      selector: { action: {} }
      default: []
    in0_triple_push:
      name: Eingang 0 – triple_push
      selector: { action: {} }
      default: []
    in0_long_push:
      name: Eingang 0 – long_push
      selector: { action: {} }
      default: []

    # Eingang 1
    in1_btn_down:
      name: Eingang 1 – btn_down
      selector: { action: {} }
      default: []
    in1_btn_up:
      name: Eingang 1 – btn_up
      selector: { action: {} }
      default: []
    in1_single_push:
      name: Eingang 1 – single_push
      selector: { action: {} }
      default: []
    in1_double_push:
      name: Eingang 1 – double_push
      selector: { action: {} }
      default: []
    in1_triple_push:
      name: Eingang 1 – triple_push
      selector: { action: {} }
      default: []
    in1_long_push:
      name: Eingang 1 – long_push
      selector: { action: {} }
      default: []

    # Eingang 2
    in2_btn_down:
      name: Eingang 2 – btn_down
      selector: { action: {} }
      default: []
    in2_btn_up:
      name: Eingang 2 – btn_up
      selector: { action: {} }
      default: []
    in2_single_push:
      name: Eingang 2 – single_push
      selector: { action: {} }
      default: []
    in2_double_push:
      name: Eingang 2 – double_push
      selector: { action: {} }
      default: []
    in2_triple_push:
      name: Eingang 2 – triple_push
      selector: { action: {} }
      default: []
    in2_long_push:
      name: Eingang 2 – long_push
      selector: { action: {} }
      default: []

    # Eingang 3
    in3_btn_down:
      name: Eingang 3 – btn_down
      selector: { action: {} }
      default: []
    in3_btn_up:
      name: Eingang 3 – btn_up
      selector: { action: {} }
      default: []
    in3_single_push:
      name: Eingang 3 – single_push
      selector: { action: {} }
      default: []
    in3_double_push:
      name: Eingang 3 – double_push
      selector: { action: {} }
      default: []
    in3_triple_push:
      name: Eingang 3 – triple_push
      selector: { action: {} }
      default: []
    in3_long_push:
      name: Eingang 3 – long_push
      selector: { action: {} }
      default: []

mode: restart

trigger:
  - platform: event
    event_type: shelly_event

condition:
  - condition: template
    value_template: "{{ trigger.event.data.device_id == device_id(shelly_device) }}"

action:
  - choose:

      # Eingang 0
      - conditions: "{{ trigger.event.data.input == 0 and trigger.event.data.event_type == 'btn_down' }}"
        sequence: !input in0_btn_down
      - conditions: "{{ trigger.event.data.input == 0 and trigger.event.data.event_type == 'btn_up' }}"
        sequence: !input in0_btn_up
      - conditions: "{{ trigger.event.data.input == 0 and trigger.event.data.event_type == 'single_push' }}"
        sequence: !input in0_single_push
      - conditions: "{{ trigger.event.data.input == 0 and trigger.event.data.event_type == 'double_push' }}"
        sequence: !input in0_double_push
      - conditions: "{{ trigger.event.data.input == 0 and trigger.event.data.event_type == 'triple_push' }}"
        sequence: !input in0_triple_push
      - conditions: "{{ trigger.event.data.input == 0 and trigger.event.data.event_type == 'long_push' }}"
        sequence: !input in0_long_push

      # Eingang 1
      - conditions: "{{ trigger.event.data.input == 1 and trigger.event.data.event_type == 'btn_down' }}"
        sequence: !input in1_btn_down
      - conditions: "{{ trigger.event.data.input == 1 and trigger.event.data.event_type == 'btn_up' }}"
        sequence: !input in1_btn_up
      - conditions: "{{ trigger.event.data.input == 1 and trigger.event.data.event_type == 'single_push' }}"
        sequence: !input in1_single_push
      - conditions: "{{ trigger.event.data.input == 1 and trigger.event.data.event_type == 'double_push' }}"
        sequence: !input in1_double_push
      - conditions: "{{ trigger.event.data.input == 1 and trigger.event.data.event_type == 'triple_push' }}"
        sequence: !input in1_triple_push
      - conditions: "{{ trigger.event.data.input == 1 and trigger.event.data.event_type == 'long_push' }}"
        sequence: !input in1_long_push

      # Eingang 2
      - conditions: "{{ trigger.event.data.input == 2 and trigger.event.data.event_type == 'btn_down' }}"
        sequence: !input in2_btn_down
      - conditions: "{{ trigger.event.data.input == 2 and trigger.event.data.event_type == 'btn_up' }}"
        sequence: !input in2_btn_up
      - conditions: "{{ trigger.event.data.input == 2 and trigger.event.data.event_type == 'single_push' }}"
        sequence: !input in2_single_push
      - conditions: "{{ trigger.event.data.input == 2 and trigger.event.data.event_type == 'double_push' }}"
        sequence: !input in2_double_push
      - conditions: "{{ trigger.event.data.input == 2 and trigger.event.data.event_type == 'triple_push' }}"
        sequence: !input in2_triple_push
      - conditions: "{{ trigger.event.data.input == 2 and trigger.event.data.event_type == 'long_push' }}"
        sequence: !input in2_long_push

      # Eingang 3
      - conditions: "{{ trigger.event.data.input == 3 and trigger.event.data.event_type == 'btn_down' }}"
        sequence: !input in3_btn_down
      - conditions: "{{ trigger.event.data.input == 3 and trigger.event.data.event_type == 'btn_up' }}"
        sequence: !input in3_btn_up
      - conditions: "{{ trigger.event.data.input == 3 and trigger.event.data.event_type == 'single_push' }}"
        sequence: !input in3_single_push
      - conditions: "{{ trigger.event.data.input == 3 and trigger.event.data.event_type == 'double_push' }}"
        sequence: !input in3_double_push
      - conditions: "{{ trigger.event.data.input == 3 and trigger.event.data.event_type == 'triple_push' }}"
        sequence: !input in3_triple_push
      - conditions: "{{ trigger.event.data.input == 3 and trigger.event.data.event_type == 'long_push' }}"
        sequence: !input in3_long_push
