blueprint:
  name: Shelly i4 Multi-Press Sensor Automation
  description: Automatisierung f체r Shelly i4 Tasten mit Short, Long, Single und Double Press 체ber Sensoren
  domain: automation
  input:
    # Sensor ausw채hlen
    shelly_sensor:
      name: Shelly i4 Sensor
      description: W채hle den Sensor, der die Taste meldet
      selector:
        entity:
          domain: sensor

    # Short Press Aktion
    short_press_action:
      name: Short Press Aktion
      selector:
        action: {}

    # Long Press Aktion
    long_press_action:
      name: Long Press Aktion
      selector:
        action: {}

    # Single Press Aktion
    single_press_action:
      name: Single Press Aktion
      selector:
        action: {}

    # Double Press Aktion
    double_press_action:
      name: Double Press Aktion
      selector:
        action: {}

trigger:
  - platform: state
    entity_id: !input "shelly_sensor"

variables:
  event: "{{ trigger.to_state.state }}"

action:
  - choose:
      - conditions: "{{ event in ['shortpush', 'S1_short', 'S2_short', 'S3_short', 'S4_short'] }}"
        sequence: !input "short_press_action"
      - conditions: "{{ event in ['longpush', 'S1_long', 'S2_long', 'S3_long', 'S4_long'] }}"
        sequence: !input "long_press_action"
      - conditions: "{{ event in ['single', 'S1_single', 'S2_single', 'S3_single', 'S4_single'] }}"
        sequence: !input "single_press_action"
      - conditions: "{{ event in ['double', 'S1_double', 'S2_double', 'S3_double', 'S4_double'] }}"
        sequence: !input "double_press_action"
