blueprint:
  name: Shelly i4 Gen3 – alle Buttons und Aktionen
  description: Steuerung aller 4 Eingänge und 6 Aktionen des Shelly i4 Gen3 über Home Assistant
  domain: automation
  input:
    device:
      name: Shelly i4 Gen3
      description: Wähle das Shelly i4 Gen3 Gerät aus
      selector:
        device:
          integration: shelly
          manufacturer: Shelly

    # Eingang 0
    in0_btn_down:
      name: Eingang 0 – btn_down
      default: []
      selector:
        action:
          optional: true
    in0_btn_up:
      name: Eingang 0 – btn_up
      default: []
      selector:
        action:
          optional: true
    in0_single_push:
      name: Eingang 0 – single_push
      default: []
      selector:
        action:
          optional: true
    in0_double_push:
      name: Eingang 0 – double_push
      default: []
      selector:
        action:
          optional: true
    in0_triple_push:
      name: Eingang 0 – triple_push
      default: []
      selector:
        action:
          optional: true
    in0_long_push:
      name: Eingang 0 – long_push
      default: []
      selector:
        action:
          optional: true

    # Eingang 1
    in1_btn_down:
      name: Eingang 1 – btn_down
      default: []
      selector:
        action:
          optional: true
    in1_btn_up:
      name: Eingang 1 – btn_up
      default: []
      selector:
        action:
          optional: true
    in1_single_push:
      name: Eingang 1 – single_push
      default: []
      selector:
        action:
          optional: true
    in1_double_push:
      name: Eingang 1 – double_push
      default: []
      selector:
        action:
          optional: true
    in1_triple_push:
      name: Eingang 1 – triple_push
      default: []
      selector:
        action:
          optional: true
    in1_long_push:
      name: Eingang 1 – long_push
      default: []
      selector:
        action:
          optional: true

    # Eingang 2
    in2_btn_down:
      name: Eingang 2 – btn_down
      default: []
      selector:
        action:
          optional: true
    in2_btn_up:
      name: Eingang 2 – btn_up
      default: []
      selector:
        action:
          optional: true
    in2_single_push:
      name: Eingang 2 – single_push
      default: []
      selector:
        action:
          optional: true
    in2_double_push:
      name: Eingang 2 – double_push
      default: []
      selector:
        action:
          optional: true
    in2_triple_push:
      name: Eingang 2 – triple_push
      default: []
      selector:
        action:
          optional: true
    in2_long_push:
      name: Eingang 2 – long_push
      default: []
      selector:
        action:
          optional: true

    # Eingang 3
    in3_btn_down:
      name: Eingang 3 – btn_down
      default: []
      selector:
        action:
          optional: true
    in3_btn_up:
      name: Eingang 3 – btn_up
      default: []
      selector:
        action:
          optional: true
    in3_single_push:
      name: Eingang 3 – single_push
      default: []
      selector:
        action:
          optional: true
    in3_double_push:
      name: Eingang 3 – double_push
      default: []
      selector:
        action:
          optional: true
    in3_triple_push:
      name: Eingang 3 – triple_push
      default: []
      selector:
        action:
          optional: true
    in3_long_push:
      name: Eingang 3 – long_push
      default: []
      selector:
        action:
          optional: true

trigger:
  - platform: device
    device_id: !input device
    domain: shelly
    type: input
    subtype: any

action:
  - choose:
      - conditions:
          - "{{ trigger.subtype == 'input:0 btn_down' }}"
        sequence: !input in0_btn_down
      - conditions:
          - "{{ trigger.subtype == 'input:0 btn_up' }}"
        sequence: !input in0_btn_up
      - conditions:
          - "{{ trigger.subtype == 'input:0 single_push' }}"
        sequence: !input in0_single_push
      - conditions:
          - "{{ trigger.subtype == 'input:0 double_push' }}"
        sequence: !input in0_double_push
      - conditions:
          - "{{ trigger.subtype == 'input:0 triple_push' }}"
        sequence: !input in0_triple_push
      - conditions:
          - "{{ trigger.subtype == 'input:0 long_push' }}"
        sequence: !input in0_long_push

      - conditions:
          - "{{ trigger.subtype == 'input:1 btn_down' }}"
        sequence: !input in1_btn_down
      - conditions:
          - "{{ trigger.subtype == 'input:1 btn_up' }}"
        sequence: !input in1_btn_up
      - conditions:
          - "{{ trigger.subtype == 'input:1 single_push' }}"
        sequence: !input in1_single_push
      - conditions:
          - "{{ trigger.subtype == 'input:1 double_push' }}"
        sequence: !input in1_double_push
      - conditions:
          - "{{ trigger.subtype == 'input:1 triple_push' }}"
        sequence: !input in1_triple_push
      - conditions:
          - "{{ trigger.subtype == 'input:1 long_push' }}"
        sequence: !input in1_long_push

      - conditions:
          - "{{ trigger.subtype == 'input:2 btn_down' }}"
        sequence: !input in2_btn_down
      - conditions:
          - "{{ trigger.subtype == 'input:2 btn_up' }}"
        sequence: !input in2_btn_up
      - conditions:
          - "{{ trigger.subtype == 'input:2 single_push' }}"
        sequence: !input in2_single_push
      - conditions:
          - "{{ trigger.subtype == 'input:2 double_push' }}"
        sequence: !input in2_double_push
      - conditions:
          - "{{ trigger.subtype == 'input:2 triple_push' }}"
        sequence: !input in2_triple_push
      - conditions:
          - "{{ trigger.subtype == 'input:2 long_push' }}"
        sequence: !input in2_long_push

      - conditions:
          - "{{ trigger.subtype == 'input:3 btn_down' }}"
        sequence: !input in3_btn_down
      - conditions:
          - "{{ trigger.subtype == 'input:3 btn_up' }}"
        sequence: !input in3_btn_up
      - conditions:
          - "{{ trigger.subtype == 'input:3 single_push' }}"
        sequence: !input in3_single_push
      - conditions:
          - "{{ trigger.subtype == 'input:3 double_push' }}"
        sequence: !input in3_double_push
      - conditions:
          - "{{ trigger.subtype == 'input:3 triple_push' }}"
        sequence: !input in3_triple_push
      - conditions:
          - "{{ trigger.subtype == 'input:3 long_push' }}"
        sequence: !input in3_long_push
