blueprint:
  name: Shelly i4 Gen3 – 4 Inputs, alle Aktionen
  description: >
    Universal Blueprint für Shelly i4 Gen3.
    Unterstützt alle 4 Eingänge (0–3) und alle Events
    (single, double, triple, long, btn_down, btn_up).
  domain: automation
  input:

    shelly_id:
      name: Shelly ID
      description: z. B. shellyi4g3-48f6ee913428
      selector:
        text:

    input_id:
      name: Eingang (0–3)
      selector:
        number:
          min: 0
          max: 3
          mode: slider

    single_push:
      name: Single Push Aktion
      default: []
      selector:
        action: {}

    double_push:
      name: Double Push Aktion
      default: []
      selector:
        action: {}

    triple_push:
      name: Triple Push Aktion
      default: []
      selector:
        action: {}

    long_push:
      name: Long Push Aktion
      default: []
      selector:
        action: {}

    btn_down:
      name: Button gedrückt (btn_down)
      default: []
      selector:
        action: {}

    btn_up:
      name: Button losgelassen (btn_up)
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: !input shelly_id
    event_data:
      device: !input shelly_id

condition:
  - condition: template
    value_template: >
      {{ trigger.event.data.input == input_id }}

action:
  - choose:

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event_type == 'single_push' }}"
        sequence: !input single_push

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event_type == 'double_push' }}"
        sequence: !input double_push

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event_type == 'triple_push' }}"
        sequence: !input triple_push

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event_type == 'long_push' }}"
        sequence: !input long_push

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event_type == 'btn_down' }}"
        sequence: !input btn_down

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event_type == 'btn_up' }}"
        sequence: !input btn_up
