blueprint:
  name: Shelly i4 Gen3 – 4 Eingänge (eine Automation)
  description: >
    Ein Blueprint für Shelly i4 Gen3 mit Geräteauswahl.
    Alle 4 Eingänge (0–3) und alle Aktionen in EINER Automation.
  domain: automation

  input:
    shelly_device:
      name: Shelly i4 Gen3
      selector:
        device:
          integration: mqtt
          manufacturer: Shelly

    # INPUT 0
    in0_single:
      name: Input 0 – Single Push
      default: []
      selector: { action: {} }
    in0_double:
      name: Input 0 – Double Push
      default: []
      selector: { action: {} }
    in0_long:
      name: Input 0 – Long Push
      default: []
      selector: { action: {} }

    # INPUT 1
    in1_single:
      name: Input 1 – Single Push
      default: []
      selector: { action: {} }
    in1_double:
      name: Input 1 – Double Push
      default: []
      selector: { action: {} }
    in1_long:
      name: Input 1 – Long Push
      default: []
      selector: { action: {} }

    # INPUT 2
    in2_single:
      name: Input 2 – Single Push
      default: []
      selector: { action: {} }
    in2_double:
      name: Input 2 – Double Push
      default: []
      selector: { action: {} }
    in2_long:
      name: Input 2 – Long Push
      default: []
      selector: { action: {} }

    # INPUT 3
    in3_single:
      name: Input 3 – Single Push
      default: []
      selector: { action: {} }
    in3_double:
      name: Input 3 – Double Push
      default: []
      selector: { action: {} }
    in3_long:
      name: Input 3 – Long Push
      default: []
      selector: { action: {} }

mode: restart

trigger:
  - platform: event
    event_type: shelly_event

condition:
  - condition: template
    value_template: >
      {{ trigger.event.data.device_id ==
         device_id(shelly_device) }}

action:
  - choose:

      # INPUT 0
      - conditions: >
          {{ trigger.event.data.input == 0 and
             trigger.event.data.event_type == 'single_push' }}
        sequence: !input in0_single

      - conditions: >
          {{ trigger.event.data.input == 0 and
             trigger.event.data.event_type == 'double_push' }}
        sequence: !input in0_double

      - conditions: >
          {{ trigger.event.data.input == 0 and
             trigger.event.data.event_type == 'long_push' }}
        sequence: !input in0_long

      # INPUT 1
      - conditions: >
          {{ trigger.event.data.input == 1 and
             trigger.event.data.event_type == 'single_push' }}
        sequence: !input in1_single

      - conditions: >
          {{ trigger.event.data.input == 1 and
             trigger.event.data.event_type == 'double_push' }}
        sequence: !input in1_double

      - conditions: >
          {{ trigger.event.data.input == 1 and
             trigger.event.data.event_type == 'long_push' }}
        sequence: !input in1_long

      # INPUT 2
      - conditions: >
          {{ trigger.event.data.input == 2 and
             trigger.event.data.event_type == 'single_push' }}
        sequence: !input in2_single

      - conditions: >
          {{ trigger.event.data.input == 2 and
             trigger.event.data.event_type == 'double_push' }}
        sequence: !input in2_double

      - conditions: >
          {{ trigger.event.data.input == 2 and
             trigger.event.data.event_type == 'long_push' }}
        sequence: !input in2_long

      # INPUT 3
      - conditions: >
          {{ trigger.event.data.input == 3 and
             trigger.event.data.event_type == 'single_push' }}
        sequence: !input in3_single

      - conditions: >
          {{ trigger.event.data.input == 3 and
             trigger.event.data.event_type == 'double_push' }}
        sequence: !input in3_double

      - conditions: >
          {{ trigger.event.data.input == 3 and
             trigger.event.data.event_type == 'long_push' }}
        sequence: !input in3_long
