blueprint:
  name: Shelly i4 Gen3 – 4 Eingänge alle Aktionen
  description: >
    Wähle oben das Shelly i4 Gerät aus und definiere Aktionen für alle 4 Eingänge.
    Jede Aktion (single, double, triple, long, btn_down, btn_up) kann pro Eingang ausgewählt werden.
  domain: automation

  input:
    shelly_device:
      name: Shelly i4 Gen3 Gerät
      description: Das Shelly i4 Gen3 Gerät auswählen
      selector:
        device:
          integration: mqtt
          manufacturer: Shelly

    input0_actions:
      name: Aktionen für Eingang 0
      description: Alle Aktionen für Eingang 0
      selector:
        action: {}

    input1_actions:
      name: Aktionen für Eingang 1
      description: Alle Aktionen für Eingang 1
      selector:
        action: {}

    input2_actions:
      name: Aktionen für Eingang 2
      description: Alle Aktionen für Eingang 2
      selector:
        action: {}

    input3_actions:
      name: Aktionen für Eingang 3
      description: Alle Aktionen für Eingang 3
      selector:
        action: {}

mode: restart

trigger:
  - platform: event
    event_type: shelly_event

condition:
  - condition: template
    value_template: >
      {{ trigger.event.data.device_id == device_id(shelly_device) }}

action:
  - choose:
      - conditions: "{{ trigger.event.data.input == 0 }}"
        sequence: !input input0_actions

      - conditions: "{{ trigger.event.data.input == 1 }}"
        sequence: !input input1_actions

      - conditions: "{{ trigger.event.data.input == 2 }}"
        sequence: !input input2_actions

      - conditions: "{{ trigger.event.data.input == 3 }}"
        sequence: !input input3_actions
